### PR TITLE
fixes path issues on windows for non-unixified paths

### LINKED ISSUE #1: patchRequire doesn't work on Windows?
First: AWESOME -- I was thinking about writing this exact same thing, but I'm happy that you did such a great job on this and it's friends (memfs, unionfs, etc...)

Now, down to brass tacks -- 

it would appear that `patchRequire` doesn't work on Windows -my guess being that that paths via memfs are always translated into unix-style and the code in `require`  knows that on windows it has to do windows-specific work.

I was going to debug into this, but any knowledge you had would be wonderful

### PR DESCRIPTION
**Pull request by fearthecowboy**
fixes #1

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1 +1 @@
-module.exports = require('lib/index');
+module.exports = require('./lib/index');
```
Comment (fearthecowboy) [inline index.js]: Given that you have a `main` in the `package.json` this file is superflous, but I used it during testing, so I found the glitch.

File: package.json [hunk 2]
```diff
@@ -25,6 +25,7 @@
     "test-coverage": "nyc --per-file mocha --compilers js:babel-core/register --require source-map-support/register --full-trace --bail src/**/*.test.js"
   },
   "dependencies": {
+    "unixify" :"1.0.0"
```
Comment (fearthecowboy) [inline package.json]: Had to take a dependency on unixify. it's not large and could be inlined, but it was critical to me. (and memfs or unionfs needs it anyway)

File: src/patchRequire.js [hunk 3]
```diff
@@ -1,6 +1,7 @@
 import * as path from 'path';
 
-
+const unixify = process.platform === 'win32' ? require('unixify') : (p)=>p;
+const correctPath = process.platform === 'win32' ? (path) => unixify( path.replace(/^\\\\\?\\.:\\/,'\\')) : (p)=>p;
```
Comment (fearthecowboy) [inline src/patchRequire.js]: I was seeing paths like  `\\?\c:\foo\bar`.

This trims the `\\?\` and unixifys the rest.

File: package.json [hunk 4]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "fs-monkey",
-  "version": "0.1.3",
+  "version": "0.1.4",
```
Comment (fearthecowboy) [inline package.json]: bumped version number for you.

File: src/correctPath.js [hunk 5]
```diff
@@ -0,0 +1,65 @@
+const isWin = process.platform === 'win32';
```
Comment (fearthecowboy) [inline src/correctPath.js]: Unixify (and the things it depends on) were needed to fix win32 support.

However, given the low-level nature of this, I opted to inline it rather than take a dependency on unixify itself. 

This reduces dependencies back to none.

File: src/correctPath.js [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+    filepath = normalizePath(filepath, stripTrailing);
+    return filepath.replace(/^([a-zA-Z]+:|\.\/)/, '');
+  }
+  return filepath;
+};
+
+/*
+* Corrects a windows path to unix format (including \\?\c:...)
+*/
+function correctPath(filepath) {
```
Comment (fearthecowboy) [inline src/correctPath.js]: Fully normalizes the paths.

**Comment by fearthecowboy** [comment]
If you'd rather have `unixify` as a dependency and not inlined, I can refactor this so it's done that way.
